CREATE TABLE IF NOT EXISTS laredo_for_lease (
    address TEXT,
    industrial_park TEXT,
    building_size INTEGER,
    space_available INTEGER,
    minimum_area INTEGER,
    office_size INTEGER,
    dock_high_doors INTEGER,
    grade_level_doors INTEGER,
    trailer_parking INTEGER,
    car_parking INTEGER,
    clear_height INTEGER,
    fire_protection TEXT,
    nnn_rate_sfpermonth REAL,
    nnn_expenses_sfpermonth REAL,
    total_gross_rate REAL,
    available_status TEXT,
    year_built INTEGER,
    construction_type TEXT,
    dock_configuration TEXT,
    contact_name TEXT,
    contact_number TEXT,
    contact_email TEXT,
    date_added TEXT,
    date_removed TEXT
);